services:
  db:
    image: postgres:latest
    container_name: kesinti-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_kesinti
      POSTGRES_DB: kesinti
    ports:
      - "7000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kesinti-net

  selenium_hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_REQUEST_TIMEOUT=900
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_PASSWORD=yeni_sifren
    ports:
      - "4444:4444"
    networks:
      - kesinti-net

  chrome-node:
    image: selenium/node-chrome:latest
    container_name: chrome-node
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=900
    shm_size: 2g
    networks:
      - kesinti-net

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "8100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "8000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped

  app:
    build:
      context: .
    env_file:
      - .env.docker
    depends_on:
      - db
      - selenium_hub
      - chrome-node
    networks:
      - kesinti-net

volumes:
  postgres_data:
    driver: local
  loki_data:
  grafana_data:

networks:
  kesinti-net:
    driver: bridge
