# docker compose -f docker-compose.yml -f docker-compose.debug.yml up
services:
  db:
    ports:
      - "7000:5432"

  selenium_hub:
    ports:
      - "4444:4444"

  app:
    ports:
      - "8000:8000"
