services:
  db:
    image: postgres:latest
    container_name: kesinti-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_kesinti
      POSTGRES_DB: kesinti
    ports:
      - "7000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local